### ISSUE TITLE
New build instructions?

### ISSUE THREAD

**Issue by NoobDoesMC** [rnine/AudioMate#26]
I'm trying to follow the build instructions from the readme, but ran into a couple problems:

`carthage` says no such option `--no-build` and the file `AMCoreAudio.xcodeproj` doesn't exist.

**Comment by rnine** [comment]
@NoobDoesMC: Sorry, the README.md was a bit outdated. I have just edited it and that should sort it out.

**Comment by NoobDoesMC** [comment]
Hey, thanks :)

I ran `carthage checkout --use-submodules` about 15 minutes ago and it's still stuck on the first step:

    *** Cloning Sparkles

**Comment by NoobDoesMC** [comment]
Oh I found it here: `./Carthage/Checkouts/AMCoreAudio/AMCoreAudio.xcodeproj`
